# Generated by Django 2.2.7 on 2019-11-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191116_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='slug',
            field=models.SlugField(default='test'),
        ),
    ]
