# Generated by Django 2.2.7 on 2019-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employerprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
