# Generated by Django 2.2.7 on 2019-11-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191127_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
