# Generated by Django 2.2.7 on 2019-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191114_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
