# Generated by Django 2.2.7 on 2019-11-18 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191116_1600'),
        ('jobs', '0003_auto_20191117_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user_fk',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.EmployerProfile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
